Move Config shared state to a Arc<RwLock<Config>>
minio/minsql pull request #68
Opened 2019-06-19 17:55 UTC by dvaldivia

This rework is needed as we will have an owner of the Config going forward that needs to be able to lock and update the configuration, this also gives the flexibility of not having to mark the Config object with a `'lifetime`

2019-06-19 19:25 UTC, harshavardhana approved these changes

2019-06-19 19:26 UTC, harshavardhana commented
Looks like some type issues @dvaldivia can you fix it?

2019-06-19 22:06 UTC, donatello requested changes
This is being reworked.

2019-06-20 00:04 UTC, harshavardhana approved these changes

2019-06-20 00:06 UTC, donatello approved these changes

2019-06-20 00:06 UTC, merged